baseURL = "https://thezenglog.netlify.com/"

languageCode = "ja"
DefaultContentLanguage = "ja"
title = "The zeng log"
theme = "hugo-theme-docdock"
#themesdir = "../.."
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

#pygmentsStyle = "monokailight"
#pygmentsStyle = "monokai"

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir= false
#enableMissingTranslationPlaceholders = false


[params]
themeStyle = "original"
#themeVariant = "blue"
themeVariant = "gray"
showVisitedLinks = false
#disableHomeIcon = true
#disableSearch = true

highlightClientSide = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[taxonomies]
#author = "authors"

[permalinks]
content = "/:filename/"